### ISSUE TITLE
Unit test fails because of missing HDF5

### ISSUE THREAD

**Issue by MarDiehl** [trilinos/trilinos.github.io#13]
When building Trilinos 12.14.1, I get the error

`error: ‘HDF5’ was not declared in this scope`.

in `Trilinos-trilinos-release-12-14-1/packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp`

I have configures Trilinos with

`cmake .. -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \                                      
             -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON \                                               
             -DTrilinos_ENABLE_Gtest:BOOL=ON \                                                      
             -DTrilinos_ENABLE_TESTS=ON \                                                           
             -DTPL_ENABLE_gtest:BOOL=ON \                                                           
             -DTPL_ENABLE_MPI:BOOL=ON \                                                             
             -DPYTHON_EXECUTABLE:PATH=/usr/bin/python2 \                                            
             -DCMAKE_INSTALL_PREFIX:PATH=/usr \                                                     
             -DBUILD_SHARED_LIBS:BOOL=ON                                                            
    make VERBOSE=1`

and HDF5 is not added automatically.

I'll now try to build explicitly with HDF5.Still, I think that the EpetraEx HDF5 unit test should be disabled if HDF5 is not added as a third partly library

**Comment by mayrmt** [comment]
@MarDiehl This is the issue board for the Trilinos website. I think you will get better and quicker developer feedback when posting to the [issue board of the Trilinos source repository](https://github.com/trilinos/Trilinos/issues).

**Comment by MarDiehl** [comment]
@mayrmt Many thanks, there is now an issue on https://github.com/trilinos/Trilinos/issues/4774

**Comment by mayrmt** [comment]
As this has moved to the Trilinos source code repository's issue board, I close this issue here.
