### ISSUE TITLE
Belos: what's the best web page to point prospective users to?

### ISSUE THREAD

**Issue by jhux2** [trilinos/trilinos.github.io#19]
@srajama1 @trilinos/belos 

@cgcgcg and I will be doing a hands-on lecture at ATPESC in early August that will involve Belos and MueLu.  Participants (mostly grad students) will be pointed to the package home pages for more information.  Is [https://trilinos.github.io/belos.html](https://trilinos.github.io/belos.html) the best and most up-to-date reference link?  Thanks.

**Comment by mhoemmen** [comment]
Not sure who added the DRAM paper to the publications list, but this doesn't look too awful.  Is this just a copy of Belos' main Doxygen page?

**Comment by jhux2** [comment]
> Not sure who added the DRAM paper to the publications list, but this doesn't look too awful. Is this just a copy of Belos' main Doxygen page?

@mhoemmen Thanks for taking a look.  I believe trilinos.org was just copied verbatim over to trilinos.github.io.  (The good old WayBack machine confirms this.)

The main thing I want to be sure of is that attendees are directed to a webpage with up-to-date, correct information.

**Comment by maherou** [comment]
The Trilinos Tutorial links have been updated.  They now point to the ATPESC tutorial as the best and most recent resource: https://github.com/trilinos/Trilinos_tutorial/wiki/TrilinosHandsOnTutorial
