### ISSUE TITLE
Trilinos (Kokkos) on MSVC (Visual Studio 19) and ICC

### ISSUE THREAD

**Issue by alessiocacciatori** [trilinos/trilinos.github.io#24]
Hi team,
  I am trying to compile entire Trilinos suite under MSVC(+ICC). Right now I managed to compile Kokkos + OpenMP but this came with quite a substantial effort and coding that raised many questions.

Basically we've found some issue that I would like to discuss before (possibly) submitting the emended code.

1) _Kokkos_HostBarrier.cpp_ Line 103. The function _try_wait(void)_ calls the static function _try_wait(int *, const int, const int)_ passing non-static members (m_buffer...). Problem is: HostBarrier methods are often called by their static methods (e.g _Kokkos_HostThreadTeam.hpp_, line 139).

This, of course, is a clear error and I am surprised on how GCC could overcome this.

2) cas128_t is defined twice (_Kokkos_AtomicAssembly.hpp_ and _Kokkos_AtomicWindows.hpp_) Solved this by removing definition in _Kokkos_AtomicAssembly.hpp_ but I am not sure what the differences are.

3) _atomic_compare_exchange_ with _cas128_t_ (_Impl::cas128_t atomic_compare_exchange<_) has a conversion error:     _tmp.t = dest;_ Indeed it is trying to convert a pointer to cas128_t to cas128_t. Solved with _tmp.t = *dest;_

4) _atomic_compare_exchange_ with SFINAE generates quite a lot of redefinition errors. Solved this by removing all SFINAE definitions and adding proper specialized bodies.

So, I am not sure if what we considered as errors are actual errors. Are we doing right with the proposed fixes (with those fixes we managed to compile Kokkos on Windows)?

Thank you in advance,
Alessio

**Comment by william76** [comment]
Hi @alessiocacciatori 

Thanks for the posting, unfortunately this is the wrong place for posting compiler issues to Trilinos... 

Please head over to https://github.com/trilinos/trilinos/issues and resubmit your ticket.  When you're there, be sure to @-mention the Kokkos team and assign the label to it for the Kokkos team as well to make sure they see it.

Cheers!
  -William

**Comment by alessiocacciatori** [comment]
Hi William
  I apologize, I am pretty new to github Thank you for your reply!

Best
 Alessio
