### ISSUE TITLE
Interfacing STRUMPACK/ButterflyPACK

### ISSUE THREAD

**Issue by keitat** [trilinos/trilinos.github.io#25]
STRUMPACK/ButterflyPack team at LBL are asking where their code should be interfaced to Trilinos. Originally, they are thinking about contributing to Amesos2, but the intended use is preconditioner.  In this case, adding an interface to other Trilinos package sounds more reasonable.  I need your advice!

STRUMPACK
https://github.com/pghysels/STRUMPACK
ButterflyPack
https://github.com/liuyangzhuan/ButterflyPACK

**Comment by ndellingwood** [comment]
Hi @keitat ! Could you file a separate issue in the Trilinos github repository https://github.com/trilinos/Trilinos/issues ? This issue will likely get more attention and responses there, thanks!

**Comment by keitat** [comment]
Will do!
