### ISSUE TITLE
where can i find the Belos example

### ISSUE THREAD

**Issue by ztdepztdep** [trilinos/trilinos.github.io#26]
I want to sue Belos to solve my linear problems. Could you please tell me where to find the tutorial of Belos.
Regards

**Comment by mhoemmen** [comment]
https://docs.trilinos.org/dev/packages/belos/doc/html/index.html

**Comment by mhoemmen** [comment]
https://docs.trilinos.org/dev/packages/belos/doc/html/examples.html

**Comment by maherou** [comment]
Last summer's ATPESC tutorial is the best resource.  You can find a pointer here: https://github.com/trilinos/Trilinos_tutorial/wiki/TrilinosHandsOnTutorial
