### ISSUE TITLE
Please add tags for the releases

### ISSUE THREAD

**Issue by Flamefire** [trilinos/trilinos.github.io#29]
It is currently unclear how to download a specific version as the source files got removed from https://trilinos.org/oldsite/download/files/ and there are no tags here.

Please tag each release with a version

**Comment by mhoemmen** [comment]
Does Trilinos even do tarball releases any more?  I think the normal way you get releases is by tag on github.com/trilinos/Trilinos.

**Comment by Flamefire** [comment]
Yes, I was confused by the big link on https://trilinos.github.io/download.html which made me come to this repo instead of https://github.com/trilinos/Trilinos

So that page should be made clearer and with an actual link which works. This one cannot even be copied ;)

Anyway, this issue can be closed

**Comment by maherou** [comment]
Dear Alexander,

Please feel free to submit a pull request with improved text.  We can benefit from community members contributions.

Thanks.

Mike
