### ISSUE TITLE
Create product area

### ISSUE THREAD

**Issue by maherou** [trilinos/trilinos.github.io#3]
We need an area in the website that replaces capability areas with product areas.  Create a products folder under pages with an overview MD page and five product pages:
- framework
- data
- linear
- nonlinear
- discretizations

**Comment by duongdo27** [comment]
Hi professor @maherou, what should be the content to put into these files? Thank you.

**Comment by maherou** [comment]
This is the mapping:
Replace the capability areas drop down with Products

With combination below:

Framework - Framework & Tools + Software Engineering Technologies
Data Services - I/O + Meshing, Geometry and Load Balancing + Scalable Linear Algebra
Linear Solvers - Linear and Eigen solvers
Nonlinear Solvers - Embedded Nonlinear Analysis Tools
Discretrizations - Discretizations

**Comment by duongdo27** [comment]
There is another field named [Parallel Programming Environments](https://trilinos.github.io/parralel_programming.html) in the **Capabilities areas**. Where I should map it to? @maherou @jwillenbring

**Comment by maherou** [comment]
This issue is fixed.
