### ISSUE TITLE
Remove non-working/misleading download links

### ISSUE THREAD

**Issue by jhux2** [trilinos/trilinos.github.io#32]
As pointed out in https://github.com/trilinos/Trilinos/issues/7260, the Trilinos github.io page has dead or misleading download links:

1. https://trilinos.github.io/download-12-0.html
2. Links on page https://trilinos.github.io/download-older.html

It would be good if users were always referred to the github release page.

**Comment by jhux2** [comment]
@maherou @victoreijkhout

**Comment by maherou** [comment]
This issue was resolved as part of a larger effort to refresh trilinos.github.io

**Comment by jhux2** [comment]
@maherou Thank you!
