### ISSUE TITLE
Trilinos user email list links are broken

### ISSUE THREAD

**Issue by jhux2** [trilinos/trilinos.github.io#42]
At the mail lists [page](https://trilinos.github.io/mail_lists.html) on trilinos.github.io, the links to the Trilinos user and announce email lists are broken.  I'd fix this, but I have no idea what the correct links are anymore.

@maherou

**Comment by maherou** [comment]
Thanks, Jonathan.  We are almost certain to switch to Slack, and away from our mail lists.  I see that the lists are MIA on trilinos.org.  Not sure why.  But we should probably just move forward with the Slack transition instead.

**Comment by jhux2** [comment]
That's good to hear.  I saw an email posted to trilinos-users on August 9 2020, so I guess the list was alive in the recent past (and maybe still is).

**Comment by jhux2** [comment]
Closing as fixed.
