### ISSUE TITLE
Regard "trilinos.sandia.gov" problem

### ISSUE THREAD

**Issue by duongdo27** [trilinos/trilinos.github.io#6]
In **Trilinos** website, there is many links in `trilinos.sandia.gov` that is not working anymore and will redirect into `trilinos.org`. Here is an example:
[http://trilinos.sandia.gov/packages/docs/dev/packages/didasko/doc/html/index.html](http://trilinos.sandia.gov/packages/docs/dev/packages/didasko/doc/html/index.html). 
Do you have any idea on handling these links? Thank you @maherou, @jwillenbring

**Comment by jwillenbring** [comment]
@duongdo27 These links mistakenly point back to an old version of the documentation. These should all be updated to the new site. The updated links should all (at least for Doxygen) be analogous to: 

[https://trilinos.org/docs/dev/packages/didasko/doc/html/index.html](https://trilinos.org/docs/dev/packages/didasko/doc/html/index.html)

**Comment by duongdo27** [comment]
Thank you. I will update the link.

**Comment by duongdo27** [comment]
List of incorrect links:
1. [http://trilinos.sandia.gov/installation_manual.html](http://trilinos.sandia.gov/installation_manual.html)
2. [http://trilinos.sandia.gov/packages/didasko/examples.html](http://trilinos.sandia.gov/packages/didasko/examples.html)
3. [http://trilinos.sandia.gov/packages/ml/doxygen/development/inline/index.html](http://trilinos.sandia.gov/packages/ml/doxygen/development/inline/index.html)
4. [http://trilinos.sandia.gov/packages/docs/dev/packages/ml/doc/html/index.html](http://trilinos.sandia.gov/packages/docs/dev/packages/ml/doc/html/index.html)
5. [http://trilinos.sandia.gov/CapabilityWebpages/GeomMeshLoadBal/GeomMeshBal_Capability.html#zoltan_ordering](http://trilinos.sandia.gov/CapabilityWebpages/GeomMeshLoadBal/GeomMeshBal_Capability.html#zoltan_ordering)
6. All the links start with "trilinos.sandia.gov" (most of them are in **Thyra** packages) in `framework.md` [raw file](https://raw.githubusercontent.com/trilinos/trilinos.github.io/master/pages/products/framework.md), [website](https://trilinos.github.io/framework_tool_and_software_engineering.html#thyra-interoperability-and-vertical-integration-of-anas)

**Comment by maherou** [comment]
All mentions of trilinos.sandia.gov are removed from this repository.
