### ISSUE TITLE
problem with io_modify.C while installation

### ISSUE THREAD

**Issue by AjaySingh40** [trilinos/trilinos.github.io#69]
**/home../trilinos/Trilinos-trilinos-release-15-1-1/packages/seacas/libraries/ioss/src/main/io_modify.C: In function ‘bool {anonymous}::handle_rename(const std::vector<std::__cxx11::basic_string >&, Ioss::Region&)’:
/home../trilinos/Trilinos-trilinos-release-15-1-1/packages/seacas/libraries/ioss/src/main/io_modify.C:1134:7: error: ‘ex_entity_type’ was not declared in this scope; did you mean ‘get_entity_type’?
1134 | ex_entity_type exo_type = Ioex::map_exodus_type(ioss_type);
| ^~~~~~~~~~~~~~
| get_entity_type
/home../trilinos/Trilinos-trilinos-release-15-1-1/packages/seacas/libraries/ioss/src/main/io_modify.C:1135:53: error: ‘exo_type’ was not declared in this scope
1135 | auto ierr = ex_put_name(exoid, exo_type, id(ge), new_name.c_str());
| ^~~~~~~~
/home../trilinos/Trilinos-trilinos-release-15-1-1/packages/seacas/libraries/ioss/src/main/io_modify.C:1135:34: error: ‘ex_put_name’ was not declared in this scope
1135 | auto ierr = ex_put_name(exoid, exo_type, id(ge), new_name.c_str());
| ^~~~~~~~~~~
/home../trilinos/Trilinos-trilinos-release-15-1-1/packages/seacas/libraries/ioss/src/main/io_modify.C:1136:19: error: ‘EX_NOERR’ was not declared in this scope
1136 | if (ierr != EX_NOERR) {
| ^~~~~~~~
/home../trilinos/Trilinos-trilinos-release-15-1-1/packages/seacas/libraries/ioss/src/main/io_modify.C:1137:9: error: ‘Ioex’ has not been declared
1137 | Ioex::exodus_error(exoid, LINE, func, FILE);

/home../trilonos/Trilinos-trilinos-release-15-1-1/packages/seacas/libraries/ioss/src/main/io_modify.C: In function ‘void {anonymous}::modify_time(Ioss::Region&, double, double)’:
/home../trilinos/Trilinos-trilinos-release-15-1-1/packages/seacas/libraries/ioss/src/main/io_modify.C:1871:5: error: ‘ex_get_all_times’ was not declared in this scope
1871 | ex_get_all_times(exoid, times.data());
| ^~~~~~~~~~~~~~~~
/home../trilinos/Trilinos-trilinos-release-15-1-1/packages/seacas/libraries/ioss/src/main/io_modify.C:1875:7: error: ‘ex_put_time’ was not declared in this scope
1875 | ex_put_time(exoid, step + 1, &times[step]);
| ^~~~~~~~~~~
[100%] Linking CXX executable shell_to_hex
[100%] Built target shell_to_hex
[100%] Linking CXX executable cth_pressure_map
make[2]: *** [packages/seacas/libraries/ioss/src/main/CMakeFiles/io_modify.dir/io_modify.C.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[100%] Built target cth_pressure_map
make[1]: *** [packages/seacas/libraries/ioss/src/main/CMakeFiles/io_modify.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable io_info
[100%] Built target io_info
[100%] Linking CXX executable sphgen
[100%] Linking CXX executable exomatlab
[100%] Linking CXX executable io_shell
[100%] Built target sphgen
[100%] Built target exomatlab
[100%] Linking CXX executable skinner
[100%] Built target io_shell
[100%] Built target skinner
make: *** [all] Error 2**

**Comment by gsjaardema** [comment]
I think there is an incorrect ifdef guarding whether exodus is/isn't enabled.  Since other exodus-related codes are being built (exomatlab, sphgen, skinner...) it looks like exodus is enabled, but `SEACAS_HAVE_EXODUS` is not being defined.   I will check to see where my logic fails.

**Comment by gsjaardema** [comment]
I guess I should ask explicitly -- does this build have Exodus enabled?

**Comment by ccober6** [comment]
Closing as this should be an issue on the Trilinos repo (https://github.com/trilinos/Trilinos).
