### ISSUE TITLE
Documentation on old sites

### ISSUE THREAD

**Issue by duongdo27** [trilinos/trilinos.github.io#7]
There are some documentations on old sites such as [https://trilinos.org/docs/files/TrilinosBuildReference.html](https://trilinos.org/docs/files/TrilinosBuildReference.html). Do you need to move them into our new site? @maherou @jwillenbring

**Comment by jwillenbring** [comment]
This is a generated file. We will need to continue to point at the file, and may need to coordinate to generating and storing the file, but the file does not need to be converted to the new site format. We will likely store this wherever we store Doxygen.

**Comment by duongdo27** [comment]
Thank you for the fast reply. So currently, I moved everything to new website already. You think what should I do next.
