### ISSUE TITLE
pdfs/mlguide5.pdf is not displayed correctly

### ISSUE THREAD

**Issue by marcfehling** [trilinos/trilinos.github.io#78]
The pdf consists of empty pages:
https://github.com/trilinos/trilinos.github.io/blob/master/pdfs/mlguide5.pdf

pdfs of older version of ML are fine:
https://github.com/trilinos/trilinos.github.io/blob/master/pdfs/mlguide4.pdf
https://github.com/trilinos/trilinos.github.io/blob/master/pdfs/mlguide31.pdf

**Comment by ccober6** [comment]
@trilinos/ml, mlguide5.pdf is not displaying correctly.  Do you have a copy that does?

**Comment by marcfehling** [comment]
> Do you have a copy that does?

In the meantime, I have found a copy hidden in the main repository
https://github.com/trilinos/Trilinos/blob/master/packages/ml/doc/mlguide.pdf

**Comment by marcfehling** [comment]
It looks like all the pdfs that https://github.com/trilinos/trilinos.github.io/commit/166b2ba42b7b001e72a4e876f8554d918a2d9360 touched ended up containing only empty pages, i.e.,
- DiscretizationCapabilityAreaOverview.pdf
- FrameworkAndToolsCA2012.pdf
- OptikaSANDReport.pdf
- TUG_Phalanx_2009_Web.pdf
- TrilinosTutorialTug2011.pdf
- mlguide5.pdf
- optikapresentation3.pdf

**Comment by rstumin** [comment]
Not sure this is worth adding ... but there is a latex file mlguide.tex that sits in packages/ml/doc/UserGuide . This is probably the most up-to-date file ... but someone would have to latex it. I did a quick attempt ... and there are some style files that I'm missing on my laptop ... but could probably find.  Again, I'm not sure that this is worth it.
